name: app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5
  video_player: ^2.4.9
  chewie: ^1.3.6
  intl: ^0.17.0
  font_awesome_flutter: ^10.3.0
  firebase_core: ^2.4.1
  cloud_firestore: ^4.3.1
  firebase_storage: ^11.0.10
  firebase_auth: ^4.2.2
  shared_preferences: ^2.2.0
  onboarding: ^3.1.0
  google_maps_flutter: ^2.5.0
  google_maps_flutter_android: ^2.5.1
  cupertino_icons: ^1.0.2
  image_picker:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/

 
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic